FROM selenium/standalone-chrome:latest

USER root

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt --break-system-packages

COPY . .

CMD ["python", "-m", "pytest", "tests/", "-v", "--tb=short"]